#!/bin/sh


mydir="$HOME/.deleted_files"
realrm="/bin/rm"
move="/bin/mv"

dest="$(pwd)"

if [ ! -d $mydir ] ; then
	echo "$(basename $0) failed: No deleted files directory. Nothing to unrm" >&2
	exit 1
fi

cd $mydir

if [ $# -eq 0 ] ; then 
	echo "Contents of your deleted file archive (sorted by date)."
	ls -t | sed -e 's/\([[:digit:]][[:digit:]]\.\)\{5\}//g' -e 's/^//'
	exit 0
fi



matches="$(ls *"$1" 2> /dev/null | wc -l)"

if [ $matches -eq 0 ] ; then
	echo "No match for \"$1\" in the deleted file archive." >&2
	exit 1
fi

if [ $matches -gt 1 ] ; then
	echo "More than one matching file or directory in the archive:"
	index=1
	for name in $(ls -td *"$1")
	do
		datetime="$(echo $name | cut -c1-14 | awk -F. '{ print $5"/"$4" at "$3":"$2":"$1 }')"
		if [ -d $name ] ; then 
			size="(ls $name | wc -l | sed 's/[^[:digit:]]//g')"
			echo " $index) 	$1 	(contents = ${size} items, deleted = $datetime)"
		else
			size="$(ls -sdk1 $name | awk '{print $1}')"
			echo " $index) 	$1 	(contents = ${size}Kb, deleted = $datetime)"
		fi
		index=$(( $index + 1 ))
	done
	echon "Which version of $1 do you want to restore? (0 to quit) [1]: "
	read desired
	if [ ${desired:=1} -ge $index ] ; then
		echo "$(basename $0) Restore canceled by user: index value too big." >&2
		exit 1
	fi

	if [ $desired -lt 1 ] ; then
		echo "$(basename $0): restore canceled by user." >&2
		exit 1
	fi

	restore="$(ls -td1 *"$1" | sed -n "${desired}p")"

	if [ -e "$dest/$1" ] ; then
		echo "\"$1\" already exists in this directory. Cannot overwrite." >&2
		exit 1
	fi

	echon "Restoring file \"$1\" ..."
	$move "$restore" "$dest/$1"
	echo "done."

	echon "Delete additional copies of this file? [y] "
	read answer

	if [ ${answer:=y} = "y" ] ; then
		$realrm -rf *"$1"
		echo "deleted."
	else
		echo "Additional copies retained."
	fi
else
	if [ -e "$dest/$1" ] ; then
		echo "\"$1\" already exists in this directory, cannot overwrite"
		exit 1
	fi

	restore="$(ls -d *"$1")"

	echon "Restoring file \"$1\"..."
	$move "$restore" "$dest/$1"
	echo "done"
fi

exit 0





